// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdWinLhnN_cP0UHBPOa6aGXRyKM2BtSmM',
    appId: '1:586392715477:web:5a089147eae6ed362ca25c',
    messagingSenderId: '586392715477',
    projectId: 'toko-online-caca7',
    authDomain: 'toko-online-caca7.firebaseapp.com',
    storageBucket: "toko-online-caca7.firebasestorage.app",
    measurementId: 'G-RMQ85W4B5Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARc7istTU0lcfhF_7xDSVmGGoR59GTVCo',
    appId: '1:586392715477:android:537c8178766502102ca25c',
    messagingSenderId: '586392715477',
    projectId: 'toko-online-caca7',
    storageBucket: 'toko-online-caca7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeQDU9wxGgsgBXRE5pj5iFK2I3GgXw_sQ',
    appId: '1:586392715477:ios:cb569500a9c830fc2ca25c',
    messagingSenderId: '586392715477',
    projectId: 'toko-online-caca7',
    storageBucket: 'toko-online-caca7.firebasestorage.app',
    iosBundleId: 'com.example.fluttertokoonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAeQDU9wxGgsgBXRE5pj5iFK2I3GgXw_sQ',
    appId: '1:586392715477:ios:cb569500a9c830fc2ca25c',
    messagingSenderId: '586392715477',
    projectId: 'toko-online-caca7',
    storageBucket: 'toko-online-caca7.firebasestorage.app',
    iosBundleId: 'com.example.fluttertokoonline',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDdWinLhnN_cP0UHBPOa6aGXRyKM2BtSmM',
    appId: '1:586392715477:web:779c660ec5757c012ca25c',
    messagingSenderId: '586392715477',
    projectId: 'toko-online-caca7',
    authDomain: 'toko-online-caca7.firebaseapp.com',
    storageBucket: 'toko-online-caca7.firebasestorage.app',
    measurementId: 'G-P49ERYRLT3',
  );
}
